FROM caio.ros:rosx11

RUN apt-get update && apt-get install -y ros-indigo-rqt \
                                         ros-indigo-rqt-common-plugins \
                                         ros-indigo-rqt-robot-plugins

CMD rqt
