version: '2'

services:
  master:
    image: ros:indigo-ros-core
    container_name: master
    command: roscore

  rqt:
    image: caio.ros:rqt
    container_name: rqt
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    environment:
      - DISPLAY
      - UID
      - GID
      - "QT_X11_NO_MITSHM=1"
      - "ROS_HOSTNAME=rqt"
      - "ROS_MASTER_URI=http://master:11311"
